### ISSUE TITLE
Random single player to server disconnect issue only happens when "MoreBuckets" is installed. Removing Fixes the issue

### ISSUE THREAD

**Issue by Zelioth** [BlakeBr0/MoreBuckets#12]
**Describe the bug**
I have been having an issue recently where when connecting to a server with the EXACT same mods as the client causes an error and disconnects the client. After days of removing, adding, and testing in a controlled environment I found that the mod is More Buckets. This may be a compatibility issue with another mod but I couldn't find another mod that caused the issue when More Buckets was included. 

**To Reproduce**
Forge, 1.20.1, Dedicated Server, Single Player. Connecting to each other this error occurs. 

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.32
 - Cucumber: 7.0.8
 - More Buckets: 4.0.2
 - Singleplayer or Multiplayer: Single player to multiplayer client

**Comment by Zelioth** [comment]
![image](https://github.com/BlakeBr0/MoreBuckets/assets/77481431/05783fb7-214c-475c-9c30-ce1a18b5280f)

Forgot to include screenshot

**Comment by BlakeBr0** [comment]
Does this issue still persist if you set `enableRecipeFixer` to false in the config?

**Comment by Zelioth** [comment]
I am not sure. I will test and find out. Now I am getting an error on startup for Iron Jet packs -_-
[crash-2024-06-04_01.32.43-fml.txt](https://github.com/user-attachments/files/15543533/crash-2024-06-04_01.32.43-fml.txt)

**Comment by Shotguun29** [comment]
Having the same issue with ver MoreBuckets-1.20.1-4.0.2.jar and 4.0.1
Running ver 4.0.0 works

**Comment by Agentx49** [comment]
same issue here

**Comment by BlakeBr0** [comment]
Do you guys have `enableRecipeFixer` set to true? I'm guessing there's some sort of incompatibility with another mod, but I can't really do anything about it without any error logs.

If the issue only started in version 4.0.1, then the only thing I can think of is that there is some weirdness with ingredients that contain modded milk buckets. If someone could test this potential fix that would be appreciated: 

https://drive.google.com/file/d/1d0XRd1gfK0lT5PpsFlMXN6yLIL3Xt_b7/view?usp=sharing

**Comment by Zelioth** [comment]
GIve me a little bit and I will test. setting up the server environment now

**Comment by Zelioth** [comment]
![image](https://github.com/user-attachments/assets/e67b8480-d8a4-405c-953d-16df5ec4c15b)
[debug.log](https://github.com/user-attachments/files/16405939/debug.log)
[latest.log](https://github.com/user-attachments/files/16405940/latest.log)


Looks like its not fixed on the latest versions of all mods, forge, and that file you shared.

**Comment by Zelioth** [comment]
Testing the enableRecipeFixer set to true now. 

changed it to false in the config file for the server. Looks like it allows connection. So whatever the recipe fixer is doing is breaking things.

**Comment by BlakeBr0** [comment]
These recipe/ingredient serialization errors are the worst because the actual error doesn't get logged from what I can tell, so I can't see where things are going wrong. It must be something to do with certain ingredient types or something another mod is doing that I'm not accounting for.

Here's another potential fix:

https://drive.google.com/file/d/14gI9OyGEF-Jqi83fyIoVwD4X2-1bOg8z/view?usp=sharing

Someone above said that version 4.0.0 didn't have this issue. If this fix doesn't work can you also confirm if that's the case?

**Comment by Zelioth** [comment]
Looks like whatever you changed allowed for the client to connect to the server without any issues. Honestly I haven't tested it but Thermal Expansion by TeamCofH has caused a bunch of issues with other mods so I wouldn't be surprised.

**Comment by BlakeBr0** [comment]
Sweet, I'll release the fix then. Hopefully it fixes all instances of this issue.
