### ISSUE TITLE
More Buckets + Cofh Core = Disconnect on Server

### ISSUE THREAD

**Issue by Mysticpasta1** [BlakeBr0/MoreBuckets#14]
**Describe the bug**
Client disconnecting from dedicated server from more buckets and cofh core interaction

**To Reproduce**
Add a thermal series mod, cofh core, cucumber, and more buckets, try to connect to a dedicated server with the same mods on the client. Experience IndexOutOfBoundsException -1 of 4

**Expected behavior**
Don't disconnect

**Screenshots / Scripts / Logs**
https://mclo.gs/aq2LDDk - this had more mods but I did test with just more buckets and cofh core with the deps needed it still did the same thing

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.3.10
 - Cucumber: 7.0.12
 - More Buckets: 4.0.3
 - Singleplayer or Multiplayer: Multiplayer

**Comment by BlakeBr0** [comment]
Does this still happen with recipe fixer disabled in the config?

**Comment by Mysticpasta1** [comment]
let me check

**Comment by BlakeBr0** [comment]
I just released version 4.0.4 which should prevent this error and log any recipes that would've caused it instead. Let me know if that fixes your case.

**Comment by Mysticpasta1** [comment]
ok let me try it :D

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
