### ISSUE TITLE
Furnace Recipes break Durability data

### ISSUE THREAD

**Issue by Davoleo** [BlakeBr0/MoreBuckets#6]
I don't know if this is on your side as a generic issue or more like a specific modpack issue, in any case I'll post it here in case anyone else is experiencing it

Minecraft Version: 1.12.2
Modpack Rustic Waters 1.3

After filling a golden bucket 1/4 of water
I've put it to cook inside a furnace and the result of that recipe is a golden bucket completely filled with purified water (4/4) despite it having just one unit of fluid before

Screenshots: 
before cooking
![image](https://user-images.githubusercontent.com/24458276/72670840-cd030080-3a42-11ea-997e-88a4fa826a7c.png)
after cooking
![image](https://user-images.githubusercontent.com/24458276/72670842-d5f3d200-3a42-11ea-9395-f7565ddf4676.png)

**Comment by BlakeBr0** [comment]
This looks like it would be either a modpack issue or an oversight by whoever added the recipe.

**Comment by Davoleo** [comment]
yep, sorry, I'll close this ticket
