### ISSUE TITLE
Update this amazing mod to 1.16.4 please

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BlakeBr0/MoreBuckets#7]
@BlakeBr0 your mods are quintessential forge mods.

**Comment by MickeyMouseYT** [comment]
Yeah please update 1.16x !!!!

**Comment by BlakeBr0** [comment]
There's now a release out for 1.18.2

https://blakesmods.com/more-buckets/download?mc_version=1.18

**Comment by MickeyMouseYT** [comment]
> There's now a release out for 1.18.2
> 
> https://blakesmods.com/more-buckets/download?mc_version=1.18

I don't want 1.18.2 i want just 1.16.5
