### ISSUE TITLE
FluidIngredient does not implement getSerializer

### ISSUE THREAD

**Issue by Shotguun29** [BlakeBr0/MoreBuckets#8]
shotguunhas disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Modders must implement Ingredient.getSerializer in their custom Ingredients: com.blakebr0.morebuckets.crafting.ingredient.FluidIngredient@2a891a0c

mod:MoreBuckets-1.18.2-2.0.0.jar
forge 40.1.31

**Comment by remplerus** [comment]
this is also not a issue friendly request.
But yes, I also get this issue when running a local forge server with MoreBuckets installed on 1.18.2
Seems you have to implement getSerializer in your Ingredient to make it work on servers :)
